language: php
php:
  - 5.5
  - 5.6

sudo: false

before_script:
  - cp .env.example .env
  - mysql -e 'create database emailservice;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan migrate:install --env=testing --no-interaction -vvv

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - vendor/bin/phpunit
  - php artisan migrate:rollback --env=testing --no-interaction -vvv

notifications:
    on_success: never
    on_failure: always